### ISSUE TITLE
Location of trained model and preprocessing script

### ISSUE THREAD

**Issue by claudeyj** [SophieHYe/SelfAPR#3]
Hi Dr. Ye, I'm really impressed by your work and I'm trying to run SelfAPR on some new bugs but I have some problems. I would be very grateful if you can help me. Specially, I didn't find the trained model in the repo. Does that mean we have to train by ourselves? In addition, how can I extract the compilation/test information from 'defects4j test' result to get something like ./dataset/test.csv? Thanks a lot for your time!

**Comment by SophieHYe** [comment]
Hi,
Please find the trained model in our Zenodo provided in the README: https://zenodo.org/record/6970846#.Y6A9ZuzMLzY

**Comment by claudeyj** [comment]
Thanks a lot!

**Comment by claudeyj** [comment]
Hi Dr. Ye, sorry to bother you again. I did checked the Zenodo link but if I understood correctly, the script along with the "dataset" are used to train the model, right? So did you also upload the trained model or we have to train by ourselves? Sorry to bother you but I just want to make sure whether we can reuse your trained mode. In addition, did you upload the preprocessing script such that given a new bug (with it's buggy line, context lines and test execution result), we could generate the "test.csv" file like [https://github.com/SophieHYe/SelfAPR/blob/main/dataset/test.csv](url) as input of the [test script](https://github.com/SophieHYe/SelfAPR/blob/03d50f08fe2f11182af359092c21fac0da237a87/5_test.py#L141). I would be very grateful if you can reply. Thanks a lot in advance!

**Comment by SophieHYe** [comment]
Hi,
Please check version 3 of Zenodo link. The trained model is included.
For the pre-process, please take a look at the perturbation model: 
java -jar perturbation-0.0.1-SNAPSHOT-jar-with-dependencies.jar test buggyLineNo-path/to/file
For example:
java -jar perturbation-0.0.1-SNAPSHOT-jar-with-dependencies.jar test 10-Demo.java
:)

**Comment by claudeyj** [comment]
Thank you so much for your answer! I can find the model now.
